### ISSUE TITLE
コンポーネントのdynamic importについて

### ISSUE THREAD

**Issue by mizushima1226** [kamiyakoh/todoapp__nextjs#2]
https://github.com/kamiyakoh/todoapp__nextjs/blob/2956006350ca4ad744722594b8b8e71da68ae80d/src/pages/active/index.tsx#L6-L8

↑のようにコンポーネントをdynamic importしていますが、それをしている事情などあれば教えて欲しいです！

**Comment by kamiyakoh** [comment]
dynamic importを使わずにActiveInnerなどのコンポーネントの内容を表示しようとすると、

> 1 of 3 unhandled errors
> Unhandled Runtime Error
> Error: Text content does not match server-rendered HTML.
> Warning: Text content did not match.
> 
> 2 of 3 unhandled errors
> Unhandled Runtime Error
> Error: Hydration failed because the initial UI does not match what was rendered on the server.
> Warning: Text content did not match.
> 
> 3 of 3 unhandled errors
> Unhandled Runtime Error
> Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
> 
> See more info here: [https://nextjs.org/docs/messages/react-hydration-error](https://nextjs.org/docs/messages/react-hydration-error)

のエラーが表示されます。

自分の認識ではnext.jsのPagesコンポーネントは基本プリレタリングするようになっており、
ローカルストレージなどサーバーに無いものからデータ読み込んでレタリングするものが含まれていると、
サーバーでプリレタリングされたものとブラウザでレタリングされたものが一致しないから上記のエラーが出ます。

なので、dynamic importを使用してクライアントレタリングする箇所を指定してnext.jsに知らせることで、
一致しない箇所が問題ないとされエラーが出なくなります。

**Comment by mizushima1226** [comment]
理解しました！！
そのような事情をコードベースでコメントしておくと、誰かが見たときに「そのコードが記述されている目的」がわかるようになります👍
（まぁ1人で開発しているので、誰かにコードの意図を伝える、を意識するのが難しいかもですが。。。）

実装していて、「xxxな込み入った事情でこういう実装になった」といった感覚があれば、その込み入った事情をコメントするとGoodだと思います👍👍👍

今回だとdynamic importしている１つ上の行に「dynamic importしないとサーバーサイドで読み込まれてエラーとなってしまうため」とかですかね🤔

**Comment by kamiyakoh** [comment]
dynamic importを含む各コンポーネントにコメントを追記しました。
